# Generated by Django 5.2.8 on 2026-01-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/version of this resume template', max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default resume template')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('portfolio_url', models.URLField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True, help_text='Professional summary or objective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('awards', 'Awards & Achievements'), ('custom', 'Custom Section')], max_length=20)),
                ('section_title', models.CharField(help_text='Display title for this section', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display sections')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='masterResume.masterresume')),
            ],
            options={
                'ordering': ['resume', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Job title, degree, skill name, etc.', max_length=300)),
                ('organization', models.CharField(blank=True, help_text='Company, university, etc.', max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(blank=True, help_text='Can be flexible format', max_length=100)),
                ('end_date', models.CharField(blank=True, help_text="Can be 'Present' or specific date", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Main description or bullet points')),
                ('link', models.URLField(blank=True, help_text='Link to project, certificate, etc.', max_length=500)),
                ('technologies', models.CharField(blank=True, help_text='Technologies/tools used', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within section')),
                ('is_active', models.BooleanField(default=True, help_text='Include in resume')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='masterResume.resumesection')),
            ],
            options={
                'ordering': ['section', 'order', '-start_date', 'id'],
            },
        ),
    ]
