# Generated by Django 5.2.8 on 2026-01-17 07:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('technical', 'Technical Interview'), ('onsite', 'On-site Interview'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('date_applied', models.DateField(default=datetime.date.today)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20)),
                ('job_description', models.TextField(blank=True)),
                ('job_url', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('work_location_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('resume_version', models.CharField(blank=True, max_length=100)),
                ('cover_letter_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_applied', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='applications.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
