# Generated by Django 5.2.8 on 2026-01-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('masterResume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='master_resume',
            field=models.ForeignKey(blank=True, help_text="Master resume this application's resume was based on", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='masterResume.masterresume'),
        ),
    ]
